// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import ConfigureAmplifyClientSide from "@/components/ConfigureAmplify";
import { AuthProvider } from "@/contexts/AuthContext";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Next.js AWS App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ConfigureAmplifyClientSide />
        <AuthProvider>
          <Navbar /> {/* Add Navbar here */}
          <main style={{ padding: '1rem' }}> {/* Add some padding */}
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}