// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ConfigureAmplify from "@/components/ConfigureAmplify";
import { AuthProvider } from "@/contexts/AuthContext";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next.js AWS App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">{/* Changed lang to ja */}
      <body className={inter.className}>
        <ConfigureAmplify /> {/* Add the configuration component here */}
        <AuthProvider>
          <Navbar /> {/* Add Navbar here */}
          <main style={{ padding: '1rem' }}> {/* Add some padding */}
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}